# Generated by Django 5.1.1 on 2025-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesiones', '0002_procesion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
