# Generated by Django 5.1.1 on 2025-12-26 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesiones', '0003_alter_procesion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesion',
            name='es_relevante',
            field=models.BooleanField(default=False, help_text='Marca esta procesión para mostrarla en el home'),
        ),
        migrations.AddField(
            model_name='procesion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesion',
            name='imagen_promocional',
            field=models.ImageField(blank=True, null=True, upload_to='procesiones/promocion/'),
        ),
    ]
