# Generated by Django 5.1.1 on 2026-01-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesiones', '0004_procesion_es_relevante_procesion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesion',
            name='turnos_devoto_local',
            field=models.PositiveIntegerField(default=5, help_text='Cantidad máxima de turnos que un devoto puede inscribirse de forma presencial.'),
        ),
        migrations.AddField(
            model_name='procesion',
            name='turnos_devoto_online',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad máxima de turnos que un devoto puede inscribirse en línea.'),
        ),
    ]
