# Generated by Django 5.1.1 on 2026-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesiones', '0005_procesion_turnos_devoto_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesion',
            name='turnos_devoto_local',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad máxima de turnos presenciales por devoto (0 = ilimitado)'),
        ),
        migrations.AlterField(
            model_name='procesion',
            name='turnos_devoto_online',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad máxima de turnos online por devoto (0 = ilimitado)'),
        ),
    ]
