# Generated by Django 5.1.1 on 2026-01-19 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesiones', '0006_alter_procesion_turnos_devoto_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procesion', models.CharField(max_length=200, verbose_name='Nombre Procesión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('relevante', models.BooleanField(default=False, help_text='Si está marcado, se mostrará en el home.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', '-fecha', '-id'],
            },
        ),
    ]
