# Generated by Django 5.1.1 on 2026-01-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesiones', '0007_postinformacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinformacion',
            name='fecha_descriptiva',
            field=models.CharField(blank=True, help_text='Ej: Quinto Sábado de Cuaresma', max_length=120, null=True, verbose_name='Fecha descriptiva'),
        ),
    ]
