# Generated by Django 4.2.18 on 2025-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('quienes_somos', '¿Quiénes somos?'), ('historia_imagenes', 'Historia de nuestras imágenes'), ('fototeca_multimedia', 'Fototeca y Multimedia'), ('marchas_funebres', 'Marchas Fúnebres'), ('recorridos_procesionales', 'Recorridos Procesionales'), ('oraciones', 'Oraciones')], max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
