# Generated by Django 4.2.18 on 2025-03-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_configuracionhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='informacion/')),
                ('informacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='aplicacion.informacion')),
            ],
        ),
    ]
