# Generated by Django 4.2.18 on 2025-03-17 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_marchafunebre_duracion_marchafunebre_favoritos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchafunebre',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marchafunebre',
            name='me_gusta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marchafunebre',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ejemplo: 5:30', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marchafunebre',
            name='favoritos',
            field=models.PositiveIntegerField(default=0, help_text='Contador de favoritos o me gusta'),
        ),
        migrations.AlterField(
            model_name='marchafunebre',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Opcional. Imagen que se mostrará como portada de la marcha.', null=True, upload_to='imagenes_marchas/'),
        ),
    ]
