# Generated by Django 5.1.1 on 2025-10-07 11:36

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaimagen',
            options={'ordering': ['orden', '-fecha_creacion']},
        ),

        # <-- EVITAR DUPLICADO DE COLUMNA 'activo'
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='historiaimagen',
                    name='activo',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),

        migrations.AddField(
            model_name='historiaimagen',
            name='fecha_creacion',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now  # para poblar filas existentes
            ),
            preserve_default=False,  # luego ya actúa auto_now_add
        ),
        migrations.AddField(
            model_name='historiaimagen',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historiaimagen',
            name='imagen',
            field=models.ImageField(upload_to='historia_imagenes/'),
        ),
        migrations.AlterField(
            model_name='historiaimagen',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
