# Generated by Django 5.1.1 on 2025-10-13 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_mediaalbum_foto_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
