# Generated by Django 5.1.1 on 2025-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_video_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='albumes/video_posters/'),
        ),
    ]
