# Generated by Django 5.1.1 on 2025-12-26 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotos', '0007_alter_devoto_correo_alter_devoto_edad'),
        ('turnos', '0005_alter_turno_marcha_funebre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevotoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devoto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='devotos.devoto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devoto_cuenta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_turno', models.CharField(max_length=50)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('lugar_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso', to='turnos.turno')),
            ],
        ),
    ]
