# Generated by Django 5.1.1 on 2025-11-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
