# Generated by Django 4.2.18 on 2025-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_alter_establecimiento_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='hermandad',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombre Hermandad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre Iglesia'),
        ),
    ]
