# Generated by Django 5.1.1 on 2026-01-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_alter_establecimiento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('acceso_mantenedor', 'Acceso al menú Mantenedor'), ('acceso_establecimiento', 'Acceso al módulo Establecimiento'), ('acceso_procesiones', 'Acceso al módulo Procesiones'), ('acceso_turnos', 'Acceso al módulo Turnos'), ('acceso_devotos', 'Acceso al módulo Devotos'), ('acceso_inscripciones', 'Acceso al módulo Inscripciones'), ('acceso_gestion_entrega', 'Acceso a Gestión de Entrega de Turnos'), ('acceso_noticias', 'Acceso al módulo Noticias'), ('crear_registro', 'Puede Crear Registro'), ('editar_registro', 'Puede Editar Registro'), ('inactivar_registo', 'Puede Inactivar Registro'), ('eliminar_registro', 'Puede Eliminar Registro'), ('abrir_reporte', 'Puede Abrir Reporte'), ('exportar_reporte', 'Puede Exportar Reporte'), ('crear_inscripcion', 'Puede Crear Inscripción'), ('anular_inscripcion', 'Puede Anular Inscripción'), ('entregar_turnos', 'Puede Enttregar Turnos'), ('crear_publicacion', 'Puede crear publicaciones'), ('editar_publicacion', 'Puede editar publicaciones'), ('eliminar_publicacion', 'Puede eliminar publicaciones'), ('turno_reservado', 'Puede inscribir en turnos reservados'), ('posts_informacion', 'Puede acceder al módulo de Posts de Información')], 'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
    ]
