# Generated by Django 5.1.1 on 2024-09-16 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotos', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('inscrito', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('devoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='devotos.devoto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='turnos.turno')),
            ],
        ),
    ]
