# Generated by Django 4.2.18 on 2025-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinscripcion',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='registroinscripcion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='registroinscripcion',
            name='valor_turno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
