# Generated by Django 4.2.18 on 2025-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0002_registroinscripcion_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinscripcion',
            name='inscrito',
            field=models.BooleanField(default=True),
        ),
    ]
