# Generated by Django 5.1.1 on 2025-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0004_registroinscripcion_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinscripcion',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
