# Generated by Django 5.1.1 on 2025-12-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0005_registroinscripcion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinscripcion',
            name='tipo_inscripcion',
            field=models.CharField(choices=[('online', 'En línea'), ('presencial', 'Presencial')], default='presencial', max_length=12),
        ),
    ]
