# Generated by Django 5.1.1 on 2024-09-16 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField(default=32)),
                ('valor', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('procesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='procesiones.procesion')),
            ],
        ),
    ]
