# Generated by Django 5.1.1 on 2024-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='marcha_funebre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
