# Generated by Django 5.1.1 on 2024-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno_marcha_funebre_turno_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='marcha_funebre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
