# Generated by Django 5.1.1 on 2025-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_turno_marcha_funebre_alter_turno_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='marcha_funebre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
