# Generated by Django 5.1.1 on 2025-12-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_turno_marcha_funebre'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='turno',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de entrega'),
        ),
    ]
