# Generated by Django 5.1.1 on 2025-12-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_turno_fecha_entrega_turno_lugar_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='nombre_hermandad_visitante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='reservado_hermandad',
            field=models.BooleanField(default=False, help_text='Turno reservado completo para una hermandad visitante'),
        ),
    ]
