# Generated by Django 5.1.1 on 2025-12-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_turno_nombre_hermandad_visitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('caballeros', 'Caballeros'), ('damas', 'Damas'), ('infantil', 'Infantil')], default='Sin Especificar', max_length=20),
        ),
    ]
