# Generated by Django 5.1.1 on 2025-12-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_turno_tipo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('sin', 'Sin especificar'), ('caballeros', 'Caballeros'), ('damas', 'Damas'), ('infantil', 'Infantil')], default='sin', max_length=20),
        ),
    ]
