# Generated by Django 5.1.1 on 2026-01-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_alter_turno_tipo_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='clase_turno',
            field=models.CharField(choices=[('ordinario', 'Ordinario'), ('extraordinario', 'Extraordinario')], default='ordinario', max_length=20),
        ),
    ]
