# Generated by Django 5.1.1 on 2026-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_turno_clase_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('sin', 'Sin especificar'), ('caballeros', 'Caballeros'), ('damas', 'Damas'), ('infantil', 'Infantil'), ('mixto', 'Mixto')], default='sin', max_length=20),
        ),
    ]
