# Generated by Django 5.1.1 on 2025-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile_apellidos_userprofile_correo_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de perfil'),
        ),
    ]
