# Generated by Django 5.1.1 on 2025-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userprofile_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estatura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estatura (cm)'),
        ),
    ]
