# Generated by Django 5.1.1 on 2025-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_userprofile_estatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género'),
        ),
    ]
