# Generated by Django 5.1.1 on 2024-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoto',
            name='codigo',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devoto',
            name='edad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
