# Generated by Django 4.2.18 on 2025-02-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotos', '0002_devoto_codigo_devoto_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devoto',
            name='cui_o_nit',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
