# Generated by Django 5.1.1 on 2025-03-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotos', '0003_devoto_activo_devoto_cui_o_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devoto',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias_devotos/'),
        ),
    ]
