# Generated by Django 5.1.1 on 2025-03-18 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotos', '0004_devoto_fecha_nacimiento_devoto_fotografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devoto',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devotos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
